### ISSUE TITLE
How to enable/disable sending of test results to TestRail using Protractor parameter?

### ISSUE THREAD

**Issue by viktorgogulenko** [Slobo989/jasmine-2-testrail#2]
Hi folks! Thank you for your 'jasmine-2-testrail' module, but while adding of it into my Protractor+Jasmine2 framework I've found one issue which little bit blocking me - as 'reporter.createRun' placed in 'afterLaunch' - I can't pass any parameter to enable/disable sending of test cases results into TestRail if Protractor parameter like '--params.sendResultsToTestRail=false' was given as on 'afterLaunch' stage all variables (even global) will be destroyed by Protractor and every time I'm receiving 'undefined' instead of needed true/false. Thanks in advance for any help regarding that.

**Comment by zeljkosimic95** [comment]
Hi, sorry you waited so long for the answer. 
We got this to work by defining the parameter in the configuration file like this:

`params: {`
    `sendResultsToTestRail: true,`
 `}`

After that, we added an 'if' statement to the 'afterLaunch' segment, like this:

`if (browser.params.sendResultsToTestRail === true) {`
`reporter.createRun(2, 13)`
`return new Promise(() => true)`
`}`

(Note the '=== true', as it will not work without it, due to how protractor handles parameter types)

Then we passed the parameter normally:

`protractor conf --params.sendResultsToTestRail=false`

In this case it doesn't create a run and send test results, and if the parameter is not defined by the user it defaults to true (so it sends the results). This can also be inverted if need be (not to send results by default)

Hope this helps, please tell us if you have any more issues with this.

**Comment by viktorgogulenko** [comment]
Hi! Thanks for answer and sorry for delay from my side - just returned from vacation. Regarding approach, mentioned by you - by some reason I've tried the same and it didn't work for me as in 'afterLaunch' step 'browser' variable seems no more existent and all the time you will be receiving 'undefined' for it. Could you please share your Protractor conf-file with structure which is working for you. I've created 'super weird solution' but at least it works for me now:

> 'use strict';
> 
> const TestRailReporter = require('jasmine-2-testrail');
> const reporter = new TestRailReporter({
> });
> let sendResults = true;
> let isTrueSetForParam;
> 
> function getArgs () {
>   const args = [];
>   process.argv
>     .slice(2, process.argv.length)
>     .forEach( arg => {
>       // long arg
>       if (arg.slice(0,2) === '--') {
>         const longArg = arg.split('=');
>         args[longArg[0].slice(2,longArg[0].length)] = longArg[1]
>       }
>       // flags
>       else if (arg[0] === '-') {
>         const flags = arg.slice(1,arg.length).split('');
>         flags.forEach(flag => {
>           args[flag] = true
>         })
>       }
>     });
>   return args;
> }
> const args = getArgs();
> 
> let sendResultsParameter = args["params.sendResultsToTestRail"];
> if(sendResultsParameter !== undefined){
>   isTrueSetForParam = (sendResultsParameter.toLowerCase() === 'true');
> }
> if(isTrueSetForParam !== true){
>   sendResults = false;
> }
> 
> exports.config = {
>     params: {
>         splitTestsBetweenCapabilities: false,
>     },
>     useAllAngular2AppRoots: true,
>     framework: 'jasmine2',
>     ignoreUncaughtExceptions: true,
>     SELENIUM_PROMISE_MANAGER: false,
>     specs: [
>         'tests/*-spec.js'
>     ],
>     capabilities: {
>             shardTestFiles: true,
>             maxInstances: 5,
>             sequential: false,
>             browserName: 'chrome',
>     },
>     onPrepare: () => {
>         let originalAddExpectationResult = jasmine.Spec.prototype.addExpectationResult;
>         jasmine.Spec.prototype.addExpectationResult = function () {
>             if (!arguments[0]) {
>                 browser.takeScreenshot().then(function (png) {
>                     allure.createAttachment('Screenshot', function () {
>                         return new Buffer(png, 'base64')
>                     }, 'image/png')();
>                 })
>             }
>             return originalAddExpectationResult.apply(this, arguments);
>         };
>         let AllureReporter = require('jasmine-allure-reporter');
>         jasmine.getEnv().addReporter(new AllureReporter({
>             resultsDir: 'allure-results',
>         }));
>         jasmine.getEnv().addReporter(reporter);
>     },
>     afterLaunch: () => {
>       if (sendResults === true) {
>         // The first parameter is the project ID, and the second is the suite ID
>         reporter.createRun(27, 141); 
>         // afterLaunch needs to return a promise in order
>         // to execute asynchronous code (used the most basic promise)
>         return new Promise(() => true)
>       }
>     }
> };

And my devdependencies with versions:

`"devDependencies": {
    "jasmine-allure-reporter": "1.0.2",
    "jasmine-2-testrail": "~1.0.10",
    "jsdoc": "^3.5.5",
    "protractor": "5.4.0",
    "protractor-console": "3.0.0",
    "testrail-api": "^1.3.5",
    "testrail": "~0.0.1"`

**Comment by zeljkosimic95** [comment]
Here is our conf file, as you can see it's much simpler than yours :

> const Reporter = require('jasmine-2-testrail')
> 
> const data = require('./data');
> 
> const reporter = new Reporter({
>   timeUnit: 'ms',
>   timeThreshold: { ok: 500, warn: 1000, ouch: 3000 },
> });
> 
> exports.config = {
>   directConnect: true,
>   baseUrl: data.URL,
>   specs: [
>     './specs/home-spec.js',
>   ],
> 
>   multiCapabilities: [
>     {
>       browserName: 'firefox',
>       // firefoxOptions: {
>       //   args: ['--headless'],
>       // },
>       // 'moz:firefoxOptions': {
>       //   args: ['--headless'],
>       // },
>     },
>   ],
> 
>   maxSessions: 1,
> 
>   jasmineNodeOpts: {
>     print: () => {},
>     showColors: true,
>   },
> 
>   onPrepare: () => {
>     browser.ignoreSynchronization = true;
>     browser.driver.manage().window().maximize();
>     jasmine.getEn
> 
> v().addReporter(reporter);
>   },
> 
>   afterLaunch: () => {
>     reporter.createRun(2, 14)
>     return new Promise(() => true)
>   },
> 
> }

We've had issues using different reporters simultaneously with our own, so that may be the issue.

**Comment by viktorgogulenko** [comment]
Thanks. Sorry, but I'm not seeing any parameter which is enabling/disabling report creation in your conf-file. Is it correct?

**Comment by zeljkosimic95** [comment]
Yes, we don't have it for now, we use a different conf file when we don't need to send results to TestRail that uses a different reporter ([jasmine-spec-reporter](https://www.npmjs.com/package/jasmine-spec-reporter)). This is also because we couldn't get the two reporters working together.
