### ISSUE TITLE
Can't create a test run from few specs (with --specs='test1-spec.js, test2-spec.js')

### ISSUE THREAD

**Issue by viktorgogulenko** [Slobo989/jasmine-2-testrail#3]
I've tried to create a test run in TestRail using just one spec and it works fine, but when I'm providing few specs (--specs='test1-spec.js, test2-spec.js') or all possible specs to run - seems jasmine-2-testrail is not able to gather results from few specs and sending empty request to TestRail:
```
[]
Created new test run: April 8, 2019, 17:14:55
Added test results
Field :results cannot be empty (one result is required)
```
Any ideas how to resolve this issue?

**Comment by Slobo989** [comment]
@viktorgogulenko Thank you for your question. Can you please send us exact command that you use for executing multiple specs? 
On our project we tried this with this command and its working fine:
`protractor --specs ./specs/test1-spec.js,./specs/test2-spec.js conf.js`

**Comment by viktorgogulenko** [comment]
I've used your way as 
`protractor  --specs ./e2e_tests/test1-spec.js,./e2e_tests/test2-spec.js protractor.conf.js --params.sendResultsToTestRail=true`

and results are the same:

> [17:55:20] I/launcher - chrome #01-0 failed 1 test(s)
> [17:55:20] I/launcher - chrome #01-1 failed 2 test(s)
> [17:55:20] I/launcher - overall: 3 failed spec(s)
> Created new test run: April 25, 2019, 17:55:20
> Added test results
> Field :results cannot be empty (one result is required)

I was using just 
`protractor  --specs='e2e_tests/*-spec.js' protractor.conf.js --params.sendResultsToTestRail=true`

Seems it sending a request to create a test run to TestRail, but it's empty - with 0 test results inside.

**Comment by Slobo989** [comment]
From this log i can only assume that some of the specs don't have test case id. Don't know what else could cause this "Field :results cannot be empty (one result is required)". If only one spec don't send result, all other results wont be sent. This solution is chosen to send all results in one network call.

**Comment by viktorgogulenko** [comment]
So, here is my protractor.conf.js file:

 
[protractor.conf.js](https://github.com/Slobo989/jasmine-2-testrail/files/3173518/protractor.conf.js.txt)

And I'm launching tests as:
`protractor protractor.conf.js --specs='e2e_tests/test1-spec.js,e2e_tests/test2-spec.js' --params.sendResultsToTestRail=true`

as a result:

> [16:48:29] I/launcher - 0 instance(s) of WebDriver still running
> [16:48:29] I/launcher - chrome #01-0 failed 7 test(s)
> [16:48:29] I/launcher - chrome #01-1 failed 1 test(s)
> [16:48:29] I/launcher - overall: 8 failed spec(s)
> Created new test run: May 13, 2019, 16:48:29
> Added test results
> Field :results cannot be empty (one result is required)

and actually new run was sent to TestRail:

<img width="1154" alt="Screenshot 2019-05-13 at 16 49 18" src="https://user-images.githubusercontent.com/12098350/57632116-24da9500-75a1-11e9-93e4-71a5bf166ea9.png">

But there is no issue if I'm running just one spec provided:

> protractor protractor.conf.js --specs='e2e_tests/test1-spec.js' --params.sendResultsToTestRail=true

> [17:05:53] I/local - Shutting down selenium standalone server.
> [17:05:53] I/launcher - 0 instance(s) of WebDriver still running
> [17:05:53] I/launcher - chrome #01 failed 7 test(s)
> [17:05:53] I/launcher - overall: 7 failed spec(s)
> Created new test run: May 13, 2019, 17:05:53
> Added test results

and proper test run was created with proper data inside.

Also if I'm trying to run just 

> protractor protractor.conf.js --specs='e2e_tests/test2-spec.js' --params.sendResultsToTestRail=true
 
it also works fine (so it's not an issue with missed test case id in these tests).

Could you try to reproduce this issue on your side using my conf-file or give me some working example which you are using? I have no idea why it doesn't work for me. Maybe I need to provide some extra module which you are using in combination with others. Thanks in advance!

**Comment by zeljkosimic95** [comment]
We've found out that the issue is in the capability "shardTestFiles", without it the tests results get sent normally. Can you try turning that off and seeing if it fixes the issue ?

**Comment by zeljkosimic95** [comment]
It seems to be a known issue with protractor #https://github.com/angular/protractor/issues/4161
The multicapabilities and the "shardTestFiles" capability both use multiple browser instances, so it seems that protractor doesn't use the defined reporter in that case.

**Comment by viktorgogulenko** [comment]
Oh, yes! It fixed an issue with sending of proper test results if I'm running bunch of specs, but without that capability we'll not be able to run tests in parallel in few threads. Is there any way to use both - your reporter and "shardTestFiles" capability?

**Comment by Slobo989** [comment]
> It seems to be a known issue with protractor #[angular/protractor#4161](https://github.com/angular/protractor/issues/4161)
> The multicapabilities and the "shardTestFiles" capability both use multiple browser instances, so it seems that protractor doesn't use the defined reporter in that case.

As @zeljkosimic95 suggested this is not fixable until this Protractor issues isn't fixed.
If you want to speed up your test process only thing that we can suggest is to use headless chrome or firefox.
