### ISSUE TITLE
Test case status remain untested in newly added test run.

### ISSUE THREAD

**Issue by vivek31** [Slobo989/jasmine-2-testrail#7]
I am observing below message whenever starting the test:

Summary:

Suites:  1 of 1
Specs:   1 of 3 (2 pending)
Expects: 1 (1 failure)
Finished in 8.421 seconds

[19:35:24] I/local - Shutting down selenium standalone server.
[19:35:24] I/launcher - 0 instance(s) of WebDriver still running
[19:35:24] I/launcher - chrome #01 failed 1 test(s)
[19:35:24] I/launcher - overall: 1 failed spec(s)
Created new test run: May 16, 2019, 19:35:24
Field :results.case_id is a required field.

**Comment by Slobo989** [comment]
@vivek31 Hi, thank you for your question. 
This could be a problem with description of your tests. 
The Case ID from TestRail must be added to the start of each it() description, 
and separated from the test name by a colon - ":"
Please check all of your it() descriptions, maybe you missed one of them. 
If that don't solves your problem, please send me your Conf file, so we can check what else could be a problem.

**Comment by vivek31** [comment]
HI @Slobo989 Thanks for the quick response. I am using the case ID properly even the case included in the newly created test run by script but it remain untested. I have attached the conf.js file here, Please review and let me know if you see anything wrong from my side.

Best Regards,
Vivek
[conf.js.txt](https://github.com/Slobo989/jasmine-2-testrail/files/3190652/conf.js.txt)

**Comment by vivek31** [comment]
Hi @Slobo989 , Did you get a chance to review the shared config file ?

Please let me know if anything else needed from my side.

Thanks,
vivek

**Comment by vivek31** [comment]
Hi @Slobo989 - Hope you are doing well!

I am just following up on this issue if you have any update for me.

Thanks,
Vivek

**Comment by Slobo989** [comment]
Hey @vivek31 ,
we still didn't figure it out what could be a problem.

**Comment by Slobo989** [comment]
@vivek31 Maybe this post could help you with setup:
https://medium.com/better-programming/sending-test-results-from-protractor-jasmine-to-testrail-e10dabf9c9bb?source=friends_link&sk=1b320d0da33fd0191301c634af6a1c60

**Comment by nikhilgupta1789** [comment]
@vivek31 @Slobo989 I am also facing the same issue, after executing the test, it created a test result in Test Rail **but not updating the result means no Pass/Fail update in Test Rail**. Could you please look into this issue.

**Comment by marcusfantinato** [comment]
@Slobo989 , @vivek31 , @BeBestOf  Hi guys!!! I'm having the same issue. Have you guys figured out what is missing? thanks a lot

**Comment by marcusfantinato** [comment]
> @Slobo989 , @vivek31 , @BeBestOf Hi guys!!! I'm having the same issue. Have you guys figured out what is missing? thanks a lot

Hi guys, I've realized that one of my test case didn't have ID.  After that it works. Pay attention in the test cases that you are running and make sure that all of them have ID.

thanks.

**Comment by Slobo989** [comment]
> > @Slobo989 , @vivek31 , @BeBestOf Hi guys!!! I'm having the same issue. Have you guys figured out what is missing? thanks a lot
> 
> Hi guys, I've realized that one of my test case didn't have ID. After that it works. Pay attention in the test cases that you are running and make sure that all of them have ID.
> 
> thanks.

For similar problems please refer to this comment.

**Comment by annbr204** [comment]
@Slobo989 I'm just trying this out and testing with one test case as below.

```
fit(‘1: Login test’, async () => {
    loginPg.navigateTo();
    loginPg.login();
    expect(await browser.getCurrentUrl()).toContain(‘/dashboard’);
  }
```
I have 50 tests in my framework and in TestRail I have only one test case. After I run the test, it doesn't create a Test Run in TestRail. I followed everything as given in your readme. I am using Typescript. The test case ID is "C1" and the name is "Login test". What am I missing?
